name: test

on:
  push: ~
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Show current versions
        run: python --version ; pip --version

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install virtualenv
        run: |
          pip install --upgrade pip
          python3.10 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

      - name: Show latest versions
        run: python --version ; pip --version

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover carys_cars
